name: Build rust
run-name: Build and test by @${{ github.actor }}
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  test:
    name: "test suite"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: cargo test
        id: cargo-test-step
        run: cargo test
