name: Build rust
run-name: Build and test by @${{ github.actor }}
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  test:
    name: "cargo test"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        id: cargo-test-step
        run: cargo test
  check-bump-vesion:
    name: "Check version bumped"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: Install pipx
        run: pipx install semver

      - name: Run check_bump_version.sh
        run: |
          pipx ensurepath
          ./check_bump_version.sh