name: Build rust
run-name: Build and test by @${{ github.actor }}
on:
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: cargo build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  test:
    name: "cargo test"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        id: cargo-test-step
        run: cargo test
  check-version-bumped:
    name: "Check version bumped"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - if: ${{ steps.cache-cargo.outputs.cache-hit == 'true' }}
        name: List cargo installed commands found in ~/.cache
        continue-on-error: true
        run: cargo --list

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Get diretories
        run: |
          uv cache dir
          uv tool install bump-my-version


      - name: Install pipx
        run: pipx install semver

      - name: Install cargo set-version
        run: cargo install cargo-edit

      - name: Run check_version_bump.sh
        run: |
          ./check_version_bump.sh
